name: Linux Health Monitor CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run unit tests (pytest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest

      - name: Test CLI modes
        run: |
          python -m agent.monitor -s > /dev/null
          python -m agent.monitor  > /dev/null
          python -m agent.monitor -a > /dev/null

      - name: Test HTML output (DEBUG)
        continue-on-error: true
        run: |
          python -m agent.monitor --html report.html

          echo "Exit code was: $?"

          ls -lah

          if [ -f report.html ]; then
            echo "HTML file created successfully"
          else
            echo "HTML file NOT created"
          fi